### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/horizon-remotedev#1]
- [x] Monitoring
- [x] Support for non-browser environment (React Native, hybrid, desktop and server side apps)
- [ ] Show actions status: loading, success, error
- [ ] Time travelling
- [ ] Reset, commit, rollback, sweep
- [ ] Cancel / skip (toggle) actions
- [ ] Export / Import state
- [ ] Dispatch actions remotely
- [ ] Recompute states on hot reloading
